import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { RootStyle } from "../components/rootStyle";
import BaseLayout from "../components/baseLayout";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <RootStyle>
          <BaseLayout>{children}</BaseLayout>
        </RootStyle>
      </body>
    </html>
  );
}
